from enum import Enum

class emgHeroActions(Enum):
    MIDDLE_FLEX = 0
    MIDDLE_EXTEND = 1
    INDEX_FLEX = 2 
    INDEX_EXTEND = 3
    THUMB_FLEX = 4
    THUMB_EXTEND = 5
    THUMB_INDEX_FLEX = 6    
    THUMB_INDEX_EXTEND = 7
    INDEX_MIDDLE_FLEX = 8
    INDEX_MIDDLE_EXTEND = 9
    THUMB_INDEX_MIDDLE_FLEX = 10
    THUMB_INDEX_MIDDLE_ETEND = 11